apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.storage.storageClass }}
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.wordpress.storage.storageClass }}
  storageClassName: {{ .Values.wordpress.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size }}
