apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
